User.create(name: '田中', employee_number: '1000', password: 'password')
User.create(name: '佐藤', employee_number: '1001', password: 'password')
User.create(name: '大庭', employee_number: '1002', password: 'password')
User.create(name: '鈴木', employee_number: '1003', password: 'password')
User.create(name: '井上', employee_number: '1004', password: 'password')
